apiVersion: "v1"
kind: Pod
metadata:
  name: master-compliance-extract
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  containers:
    - name: compliance-extract-pod
      image: registry.access.redhat.com/ubi8/ubi
      command: ["sleep", "3000"]
      volumeMounts:
#      - mountPath: "/workers-scan-results"
#        name: workers-scan-vol
      - mountPath: "/masters-scan-results"
        name: masters-scan-vol
#      - mountPath: "/cis-scan-results"
#        name: cis-scan-vol
  volumes:
#    - name: workers-scan-vol
#      persistentVolumeClaim:
#        claimName: ocp4-cis-node-worker
    - name: masters-scan-vol
      persistentVolumeClaim:
        claimName: ocp4-cis-node-master
#    - name: cis-scan-vol
#      persistentVolumeClaim:
#        claimName: ocp4-cis
